export const getFlag = (country) => {
  switch (country) {
    case 'USA':
      return 'https://www.amcharts.com/wp-content/uploads/flags/united-states.svg';
    case 'EU':
      return 'https://www.amcharts.com/wp-content/uploads/flags/european-union.svg';
    case 'AUS':
      return 'https://www.amcharts.com/wp-content/uploads/flags/australia.svg';
    case 'ARG':
      return 'https://www.amcharts.com/wp-content/uploads/flags/argentina.svg';
    case 'BRA':
      return 'https://www.amcharts.com/wp-content/uploads/flags/brazil.svg';
    case 'IND':
      return 'https://www.amcharts.com/wp-content/uploads/flags/india.svg';
    case 'CHN':
      return 'https://www.amcharts.com/wp-content/uploads/flags/china.svg';
    case 'RUS':
      return 'https://www.amcharts.com/wp-content/uploads/flags/russia.svg';
    case 'CHL':
      return 'https://www.amcharts.com/wp-content/uploads/flags/chile.svg';
    case 'BOL':
      return 'https://www.amcharts.com/wp-content/uploads/flags/bolivia.svg';
    case 'SGP':
      return 'https://www.amcharts.com/wp-content/uploads/flags/singapore.svg';
    case 'HKG':
      return 'https://www.amcharts.com/wp-content/uploads/flags/hong-kong.svg';
    case 'MEX':
      return 'https://www.amcharts.com/wp-content/uploads/flags/mexico.svg';
    case 'CAN':
      return 'https://www.amcharts.com/wp-content/uploads/flags/canada.svg';
    case 'SAU':
      return 'https://www.amcharts.com/wp-content/uploads/flags/saudi-arabia.svg';
    case 'MYS':
      return 'https://www.amcharts.com/wp-content/uploads/flags/malaysia.svg';
    case 'VNM':
      return 'https://www.amcharts.com/wp-content/uploads/flags/vietnam.svg';
    case 'PHL':
      return 'https://www.amcharts.com/wp-content/uploads/flags/philippines.svg';
    case 'EGY':
      return 'https://www.amcharts.com/wp-content/uploads/flags/egypt.svg';
    case 'ZAF':
      return 'https://www.amcharts.com/wp-content/uploads/flags/south-africa.svg';
    case 'ESP':
      return 'https://www.amcharts.com/wp-content/uploads/flags/spain.svg';
    case 'JPN':
      return 'https://www.amcharts.com/wp-content/uploads/flags/japan.svg';
    case 'KAZ':
      return 'https://www.amcharts.com/wp-content/uploads/flags/kazakhstan.svg';
    case 'NZL':
      return 'https://www.amcharts.com/wp-content/uploads/flags/new-zealand.svg';
    case 'SDN':
      return 'https://www.amcharts.com/wp-content/uploads/flags/sudan.svg';
    case 'LBY':
      return 'https://www.amcharts.com/wp-content/uploads/flags/libya.svg';
    case 'TUR':
      return 'https://www.amcharts.com/wp-content/uploads/flags/turkey.svg';
    case 'PER':
      return 'https://www.amcharts.com/wp-content/uploads/flags/peru.svg';
    case 'SVK':
      return 'https://www.amcharts.com/wp-content/uploads/flags/slovakia.svg';
    case 'ROU':
      return 'https://www.amcharts.com/wp-content/uploads/flags/romania.svg';
    case 'HRV':
      return 'https://www.amcharts.com/wp-content/uploads/flags/croatia.svg';
    case 'POL':
      return 'https://www.amcharts.com/wp-content/uploads/flags/republic-of-poland.svg';
    case 'DEU':
      return 'https://www.amcharts.com/wp-content/uploads/flags/germany.svg';
    case 'BLR':
      return 'https://www.amcharts.com/wp-content/uploads/flags/belarus.svg';
    case 'UKR':
      return 'https://www.amcharts.com/wp-content/uploads/flags/ukraine.svg';
    case 'FRA':
      return 'https://www.amcharts.com/wp-content/uploads/flags/france.svg';
    case 'SWE':
      return 'https://www.amcharts.com/wp-content/uploads/flags/sweden.svg';
    case 'ITA':
      return 'https://www.amcharts.com/wp-content/uploads/flags/italy.svg';
    case 'LUX':
      return 'https://www.amcharts.com/wp-content/uploads/flags/luxembourg.svg';
    case 'SVN':
      return 'https://www.amcharts.com/wp-content/uploads/flags/slovenia.svg';
    case 'COD':
      return 'https://www.amcharts.com/wp-content/uploads/flags/democratic-republic-of-congo.svg';
    case 'DZA':
      return 'https://www.amcharts.com/wp-content/uploads/flags/algeria.svg';
    case 'NAM':
      return 'https://www.amcharts.com/wp-content/uploads/flags/namibia.svg';
    case 'GRL':
      return 'https://www.amcharts.com/wp-content/uploads/flags/greenland.svg';
    case 'SRB':
      return 'https://www.amcharts.com/wp-content/uploads/flags/serbia.svg';
    case 'AUT':
      return 'https://www.amcharts.com/wp-content/uploads/flags/austria.svg';
    case 'HUN':
      return 'https://www.amcharts.com/wp-content/uploads/flags/hungary.svg';
    case 'NOR':
      return 'https://www.amcharts.com/wp-content/uploads/flags/norway.svg';
    case 'ETH':
      return 'https://www.amcharts.com/wp-content/uploads/flags/ethiopia.svg';
    case 'KEN':
      return 'https://www.amcharts.com/wp-content/uploads/flags/kenya.svg';
    case 'ARE':
      return 'https://www.amcharts.com/wp-content/uploads/flags/united-arab-emirates.svg';
    case 'IRN':
      return 'https://www.amcharts.com/wp-content/uploads/flags/iran.svg';
    case 'FIN':
      return 'https://www.amcharts.com/wp-content/uploads/flags/finland.svg';
    case 'COL':
      return 'https://www.amcharts.com/wp-content/uploads/flags/colombia.svg';
    case 'ZMB':
      return 'https://www.amcharts.com/wp-content/uploads/flags/zambia.svg';
    case 'VAT':
      return 'https://www.amcharts.com/wp-content/uploads/flags/vatican-city.svg';
    case 'THA':
      return 'https://www.amcharts.com/wp-content/uploads/flags/thailand.svg';
    case 'EST':
      return 'https://www.amcharts.com/wp-content/uploads/flags/estonia.svg';
    case 'NGA':
      return 'https://www.amcharts.com/wp-content/uploads/flags/nigeria.svg';
    case 'MNG':
      return 'https://www.amcharts.com/wp-content/uploads/flags/mongolia.svg';
    case 'BWA':
      return 'https://www.amcharts.com/wp-content/uploads/flags/botswana.svg';
    case 'CYM':
      return 'https://www.amcharts.com/wp-content/uploads/flags/cayman-islands.svg';
    default:
      break;
  }
};
